name: main-workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: myrunner
    steps:
      - name: Run a online script
        run: echo "Running WorkFlow in main branch"
      - name: Another runner
        run: echo "This is from a different runner"
