name: main-workflow2
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: eho "build started"
        continue-on-error: true
      - run: echo "build ended"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "test started"
      - run: eho "test ended"      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy started"
      - run: echo "deploy ended"
    needs: test
    if: ${{ always() }}
