name: main-workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: myrunner
    steps:
      - name: Run a online script
        run: |
          echo "Running WorkFlow in main branch"
          hostname
          sleep 5
          touch /tmp/fabricio13jun
      - name: second step
        run: echo "Hello from second step"
        if: github.event_name == 'push'
      - name: third step
        run: echo "hello"
